-
  name: 'Execute a script on all web server nodes'
  hosts: all_servers
  # start mysql service only on mysql server
  tasks:
    -
      service: 'name=mysql state=started'
      when: 'ansible_host=="server4.company.com"'