---
- name: Check status of a service and email if it is down
  hosts: localhost
  tasks:
    - command: service httpd status
      register: result

    - mail:
        to: admin@company.com
        subject: Service Alert
        body: Httpd Service is down
        # when result stdout has down in it where result is what is registered from the output of  an earlier task
        when: result.stdout.find('down') != -1